name: Notificar Telegram

on:
  schedule:
    - cron: '0 * * * *'  # roda de hora em hora, no minuto 0
    
  workflow_dispatch:      # também pode rodar manualmente

jobs:
  executar-script:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: pip install requests

      - name: Executar script
        run: python main.py
